[package]
name = "sniffer"
version = "0.1.0"
authors = ["Ivan Nikitin <nikitin.ivan.dev@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
argparse = "0.2.2"
pcap = { version = "0.8", features = ["capture-stream"] }
rust-s3 = "0.26.4"
futures = "0.3"
tokio = "0.2"